config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/thankyou'

  get 'static_pages/contribute'

  get 'static_pages/contact'

  post 'static_pages/thank_you'

  post 'static_pages/contribute_thank_you'

  resources :trails
  get 'static_pages/coming_soon'

  get 'static_pages/index'
  root 'static_pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trail.rb
class Trail < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@email, @name, @message).deliver_now
  end

  def contribute_thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    @strava_route = params[:strava_route]
    UserMailer.contribute_form(@email, @name, @message, @strava_route).deliver_now
  end


end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, only: [:show, :edit, :update, :destroy]

  # GET /trails
  # GET /trails.json
  def index
    @trails = Trail.all
  end

  # GET /trails/1
  # GET /trails/1.json
  def show
  end

  # GET /trails/new
  def new
    @trail = Trail.new
  end

  # GET /trails/1/edit
  def edit
  end

  # POST /trails
  # POST /trails.json
  def create
    @trail = Trail.new(trail_params)

    respond_to do |format|
      if @trail.save
        format.html { redirect_to @trail, notice: 'Trail was successfully created.' }
        format.json { render :show, status: :created, location: @trail }
      else
        format.html { render :new }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trails/1
  # PATCH/PUT /trails/1.json
  def update
    respond_to do |format|
      if @trail.update(trail_params)
        format.html { redirect_to @trail, notice: 'Trail was successfully updated.' }
        format.json { render :show, status: :ok, location: @trail }
      else
        format.html { render :edit }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trails/1
  # DELETE /trails/1.json
  def destroy
    @trail.destroy
    respond_to do |format|
      format.html { redirect_to trails_url, notice: 'Trail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trail
      @trail = Trail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trail_params
      params.require(:trail).permit(:name, :distance, :route_id, :difficulty_level, :terrain, :elevation, :overview, :header_image, :image_one, :image_two, :image_three, :handy_hint, :trail_icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trail Run Sydney</title>
    
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/instafeed.js/1.4.1/instafeed.min.js"></script>
    <script type="text/javascript">

    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Fjalla+One|Montserrat:200,400i,400,500,600,700,700i" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  </head>

  <body>
    <nav class="navbar navbar-default" id="top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/static_pages/index"><%= image_tag("TRS_Logo_06-01.png", :alt => "trs-logo", :class => "img-responsive trs-nav-logo") %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "HOME", '/' %></li>
            <li><%= link_to "TRAILS", trails_path %></li>
            <li><%= link_to "CONTACT", '/static_pages/contact' %></li>
            <li><%= link_to "SHARE YOUR KNOWLEDGE", '/static_pages/contribute' %></li>
            <li><a href="https://www.instagram.com/trailrunsydney/" target="_blank" class="social-media-links"><i class="fa fa-instagram social-media-insta" aria-hidden="true"></i></a></li>
            <li><a href="#" class="social-media-links"><i class="fa fa-facebook social-media-fb" aria-hidden="true"></i></a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <%= yield %>
    <div class="footer">
      <h4 class="footer-header"><a href="#top" class="basic-link">BACK TO TOP</a></h4>
      <div class="row footer-row">
        <div class="col-xs-6 col-sm-4 col-md-4">
          <p class="footer-paragraph">EMAIL<br><a href="mailto:hello@trailrunsydney.com" class="footer-link">hello@trailrunsydney.com</a></p>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-4">
          <p class="footer-paragraph">JOIN THE TRS CLUB<br><span class="italic"><a href="https://www.instagram.com/explore/tags/trailrunsydney/" target="_blank" class="footer-link">#trailrunsydney</a></span></p>
        </div>
        <div class="footer-media-links col-xs-12 col-sm-4 col-md-4">
          <a href="https://www.instagram.com/trailrunsydney/" target="_blank" class="social-media-links"><i class="fa fa-instagram social-media-insta" aria-hidden="true"></i></a>
          <a href="https://www.instagram.com/trailrunsydney/" target="_blank" class="social-media-links"><i class="fa fa-facebook social-media-fb" aria-hidden="true"></i></a>
        </div>
      </div>
      <footer>
        <p>Design: <a href="http://www.georgiamather.com/" target="_blank">www.georgiamather.com</a> | Development: <a href="http://www.nicfisher.co/" target="_blank">Nic Fisher</a> | @ All Rights Reserved</p>
      </footer>
    </div>
  </body>
</html>

app/views/static_pages/coming_soon.html.erb
<div class="hero">
  <div class="main-page-header">
    <h1>OPPS! THIS PAGE ISNT READY YET</h1>
    <p>FOLLOW US ON INSTAGRAM FOR WEBSITE UPDATES.<br><a href="https://www.instagram.com/trailrunsydney/" target="_blank"class="basic-link coming-soon-link">@TRAILRUNSYDNEY</a></p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="contact-container">
  <div class="trail-header">
    <h3>CONTACT US</h3>
  </div>
  <%= flash[:notice] %>

  <%= form_tag("/static_pages/thank_you") do %>
    <div class="contact-form">
      <div class="form-group">
        <%= label_tag :name, "Name*" %>
        <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name", required: "true"%>
      </div>      
      <div class="form-group">
        <%= label_tag :email, "Email Address*" %>
        <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email", required: "true", type: "email" %>
      </div>
      <div class="form-group">
        <%= label_tag :message, "Message*" %>
        <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message", required: "true" %>
      </div>
      <button class="btn btn-primary">
        <%= submit_tag "SEND" %>
      </button>      
    </div>
  <% end %>
</div>

app/views/static_pages/contribute.html.erb
<div class="contribute-container">
  <div class="trail-header">
    <h3>CONTRIBUTE</h3>
  </div>
  <%= flash[:notice] %>
  <p class="contribute-paragraph">We are always looking for new running trails to share with the community and would love your help.<br>
  If possible, please add the Strava Route URL. This can be created <a href="https://www.strava.com/routes/new" target="_blank">here</a>.</p>
  <%= form_tag("/static_pages/contribute_thank_you") do %>
    <div class="contact-form">
      <div class="form-group">
        <%= label_tag :name %>
        <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
      </div>      
      <div class="form-group">
        <%= label_tag :email, "Email Address*" %>
        <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email", required: "true", type: "email" %>
      </div>
      <div class="form-group">
        <%= label_tag :strava_route, "Strava Route" %>
        <%= text_field_tag :strava_route, nil, class: "form-control", placeholder: "Enter Strava Route URL" %>
      </div>
      <div class="form-group">
        <%= label_tag :message, "Trail Details*" %>
        <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Trail Details", required: "true" %>
      </div>
      <button class="btn btn-primary">
        <%= submit_tag "SEND" %>
      </button>      
    </div>
  <% end %>
</div>

app/views/static_pages/contribute_thank_you.html.erb
<div class="thankyou-container">
  <div class="trail-header">
    <h3>THANK YOU FOR YOUR CONTRIBUTION</h3>
  </div>
  <p>We have received your message and will respond as soon as possible.</p>
  <%= link_to "BACK TO HOME", '/static_pages/index', class:'green-link' %>
</div>

app/views/static_pages/index.html.erb
<div class="hero">
  <div class="main-page-header">
    <h1>RUN. EXPLORE. ESCAPE THE CITY</h1>
    <p><span>TrailRunSydney.com </span><br>your one-stop guide to discovering Sydney’s running trails <br>that are right on your doorstep.</p>
    <%= link_to "EXPLORE HERE", '/trails', class:'green-link' %>
    <div class="down-arrow">
      <a href="#about"><i class="fa fa-chevron-down" aria-hidden="true"></i></a>
    </div>
  </div>
</div>

<div id="about-container">
  <div class="row about-row" id="about">
    <div class="col-xs-4 col-sm-4 col-md-4">
    </div>
    <div class="col-xs-12 col-sm-8 col-md-8">
      <h2>WHO WE ARE</h2>
      <h3>LIKE RUNNING?</h3>
      <h3>LIKE EXPLORING? LIKE ESCAPING THE CITY PRESSURE?</h3>
      <div class="orange-line">
      </div>
    </div>
  </div>

  <div class="row about-row">
    <div class="col-xs-8 col-sm-4 col-md-4">
      <%= image_tag("nic-fisher.png", :alt => "nic-fisher", :class => "img-responsive profile-img") %> 
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4">
      <p><span class="strong">Me too.<br>
      My name is Nic Fisher and I really enjoy getting off the concrete and running the leafy trails that wind their way across Sydney.</span><br>
      <span class="strong italic">That is when I could find them.</span><br><br>
      Too often I'd have to play detective and piece together a map, where to park, was there any public transport. By the time I'd found all this it was too late to start or I'd just had the desire sucked out of me and I'd pound the pavement once again.<br><br>
      Enough is enough. I want to do something about this and I want <span class="strong underlined">YOU</span> to join me.</p>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4">
      <p class="margin-bottom">Right now I'm collating all the data - and having a blast doing it mind you - by running and recording as much as I can.<br><br>
      I want you to be involved. I want this to be a community project. More sets of legs, more eyes on the trails, more ears to the ground, the better this becomes for all of us.<br><br>
      If you would like to be a part of this, make some running friends, maybe learn new skills and get a few dopamine hits along the way then dont be shy, say hi.</p>
      <%= link_to "CONTRIBUTE", '/static_pages/contribute', class:'green-link' %>
    </div>
  </div>

</div>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-91957200-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/thank_you.html.erb
<div class="thankyou-container">
  <div class="trail-header">
    <h3>THANK YOU</h3>
  </div>
  <p>We have received your message and will respond as soon as possible.</p>
  <%= link_to "BACK TO HOME", '/static_pages/index', class:'green-link' %>
</div>

app/views/trails/_form.html.erb
<%= form_for(trail) do |f| %>
  <% if trail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trail.errors.count, "error") %> prohibited this trail from being saved:</h2>

      <ul>
      <% trail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :route_id %>
    <%= f.number_field :route_id, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :difficulty_level %>
    <%= f.text_field :difficulty_level, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :distance %>
    <%= f.text_field :distance, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :terrain %>
    <%= f.text_field :terrain, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :elevation %>
    <%= f.number_field :elevation, class: "form-control" %>
  </div>

    <div class="field">
    <%= f.label :trail_icon %>
    <%= f.text_field :trail_icon, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :overview %>
    <%= f.text_area :overview, size: '10x6', class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :header_image %>
    <%= f.text_field :header_image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :image_one %>
    <%= f.text_field :image_one, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :image_two %>
    <%= f.text_field :image_two, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :image_three %>
    <%= f.text_field :image_three, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :handy_hint %>
    <%= f.text_area :handy_hint, size: '10x6', class: "form-control" %>
  </div>

  <button class="actions green-link">
    <%= f.submit %>
  </button>


<% end %>

app/views/trails/edit.html.erb
<div class="container">
  <h1>Editing Trail</h1>

  <%= render 'form', trail: @trail %>

  <%= link_to 'Show', @trail %> |
  <%= link_to 'Back', trails_path %>
</div>

app/views/trails/index.html.erb
<div class="trail-header">
  <h3>LET'S HIT THE TRAILS</h3>
</div>

<div class="row trail-row">
  <% @trails.each do |trail| %>
    <div class="col-xs-12 col-sm-4 col-md-4 trail-column">
      <%= link_to trail do %>
        <div class="img-overlay">
          <%= image_tag(trail.image_one, class: "img-responsive small-trail-img") %>
          <div class="index-overlay">
            <%= image_tag(trail.trail_icon, class: "trail-icon") %>
            <h4><%= trail.name %></h4>
            <div class="small-orange-line">
            </div>
            <p><%= trail.distance %> | <%= trail.difficulty_level %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<br>

<!-- <div>
<%= link_to 'New Trail', new_trail_path %>
</div> -->

app/views/trails/new.html.erb
<h1>New Trail</h1>

<%= render 'form', trail: @trail %>

<%= link_to 'Back', trails_path %>

app/views/trails/show.html.erb
<div class="show-header-image">
  <%= image_tag(@trail.header_image, class: "img-responsive large-header-img") %>
    <h3><%= @trail.name %></h3>
</div>

<div class="trail-info-container container">
  <h4>OVERVIEW</h4>
  <div class="small-orange-line">
  </div>
  <p class="overview"><%= @trail.overview %></p>
  <div class="the-basics">
    <div class="the-basics-header">
      <h4>THE BASICS</h4>
    </div>
    <div class="basic-info">
    <p>
      <strong>DIFFICULTY LEVEL:</strong>
      <%= @trail.difficulty_level %>
    </p>
    <p>
      <strong>DISTANCE:</strong>
      <%= @trail.distance %>
    </p>
    <p>
      <strong>TERRAIN:</strong>
      <%= @trail.terrain %>
    </p>
    <p>
      <strong>ELEVATION:</strong>
      <%= @trail.elevation %> METRES
    </p>
    <p>
    <strong>HANDY HINT:</strong>
      <%= @trail.handy_hint %>
    </p>
    </div>
  </div>

  <iframe src="https://www.doogal.co.uk/StravaRoute.php?id=<%= @trail.route_id %>&embed=true&segments=false&title=false&streetView=false"
 width="600" height="850" frameborder="0"></iframe>
  
  <div class="instagram-feed">
    <p>Join the TRC team. #trailrunsydney</p>
  <div id="instafeed"></div>
    
  </div>

</div>

<div class="back-to-trails">
  <%= link_to 'Back To Trails', trails_path, class:'green-link' %>
</div>